/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTerritoryRouteImport } from './routes/_authenticated/territory'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdversariesRouteImport } from './routes/_authenticated/adversaries'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedAlertsAlertIdRouteImport } from './routes/_authenticated/alerts.$alertId'
import { Route as ApiPublicHooksScanNewsRouteImport } from './routes/api/public/hooks/scan-news'
import { Route as ApiPublicHooksScanInstagramRouteImport } from './routes/api/public/hooks/scan-instagram'
import { Route as ApiPublicHooksPurgeRetentionRouteImport } from './routes/api/public/hooks/purge-retention'
import { Route as ApiPublicHooksGenerateReportsRouteImport } from './routes/api/public/hooks/generate-reports'
import { Route as ApiPublicHooksDetectAlertsRouteImport } from './routes/api/public/hooks/detect-alerts'
import { Route as ApiPublicHooksAnalyzePendingRouteImport } from './routes/api/public/hooks/analyze-pending'
import { Route as ApiPublicEvolutionWebhookTokenRouteImport } from './routes/api/public/evolution.webhook.$token'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerritoryRoute = AuthenticatedTerritoryRouteImport.update({
  id: '/territory',
  path: '/territory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdversariesRoute =
  AuthenticatedAdversariesRouteImport.update({
    id: '/adversaries',
    path: '/adversaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedAlertsAlertIdRoute =
  AuthenticatedAlertsAlertIdRouteImport.update({
    id: '/$alertId',
    path: '/$alertId',
    getParentRoute: () => AuthenticatedAlertsRoute,
  } as any)
const ApiPublicHooksScanNewsRoute = ApiPublicHooksScanNewsRouteImport.update({
  id: '/api/public/hooks/scan-news',
  path: '/api/public/hooks/scan-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanInstagramRoute =
  ApiPublicHooksScanInstagramRouteImport.update({
    id: '/api/public/hooks/scan-instagram',
    path: '/api/public/hooks/scan-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPurgeRetentionRoute =
  ApiPublicHooksPurgeRetentionRouteImport.update({
    id: '/api/public/hooks/purge-retention',
    path: '/api/public/hooks/purge-retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateReportsRoute =
  ApiPublicHooksGenerateReportsRouteImport.update({
    id: '/api/public/hooks/generate-reports',
    path: '/api/public/hooks/generate-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDetectAlertsRoute =
  ApiPublicHooksDetectAlertsRouteImport.update({
    id: '/api/public/hooks/detect-alerts',
    path: '/api/public/hooks/detect-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAnalyzePendingRoute =
  ApiPublicHooksAnalyzePendingRouteImport.update({
    id: '/api/public/hooks/analyze-pending',
    path: '/api/public/hooks/analyze-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionWebhookTokenRoute =
  ApiPublicEvolutionWebhookTokenRouteImport.update({
    id: '/api/public/evolution/webhook/$token',
    path: '/api/public/evolution/webhook/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/adversaries': typeof AuthenticatedAdversariesRoute
  '/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/news': typeof AuthenticatedNewsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/territory': typeof AuthenticatedTerritoryRoute
  '/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/api/public/hooks/analyze-pending': typeof ApiPublicHooksAnalyzePendingRoute
  '/api/public/hooks/detect-alerts': typeof ApiPublicHooksDetectAlertsRoute
  '/api/public/hooks/generate-reports': typeof ApiPublicHooksGenerateReportsRoute
  '/api/public/hooks/purge-retention': typeof ApiPublicHooksPurgeRetentionRoute
  '/api/public/hooks/scan-instagram': typeof ApiPublicHooksScanInstagramRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/evolution/webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/adversaries': typeof AuthenticatedAdversariesRoute
  '/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/news': typeof AuthenticatedNewsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/territory': typeof AuthenticatedTerritoryRoute
  '/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/api/public/hooks/analyze-pending': typeof ApiPublicHooksAnalyzePendingRoute
  '/api/public/hooks/detect-alerts': typeof ApiPublicHooksDetectAlertsRoute
  '/api/public/hooks/generate-reports': typeof ApiPublicHooksGenerateReportsRoute
  '/api/public/hooks/purge-retention': typeof ApiPublicHooksPurgeRetentionRoute
  '/api/public/hooks/scan-instagram': typeof ApiPublicHooksScanInstagramRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/evolution/webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/adversaries': typeof AuthenticatedAdversariesRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/territory': typeof AuthenticatedTerritoryRoute
  '/_authenticated/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/api/public/hooks/analyze-pending': typeof ApiPublicHooksAnalyzePendingRoute
  '/api/public/hooks/detect-alerts': typeof ApiPublicHooksDetectAlertsRoute
  '/api/public/hooks/generate-reports': typeof ApiPublicHooksGenerateReportsRoute
  '/api/public/hooks/purge-retention': typeof ApiPublicHooksPurgeRetentionRoute
  '/api/public/hooks/scan-instagram': typeof ApiPublicHooksScanInstagramRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/evolution/webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/adversaries'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/groups'
    | '/news'
    | '/onboarding'
    | '/people'
    | '/reports'
    | '/search'
    | '/settings'
    | '/sources'
    | '/territory'
    | '/alerts/$alertId'
    | '/reports/$reportId'
    | '/api/public/hooks/analyze-pending'
    | '/api/public/hooks/detect-alerts'
    | '/api/public/hooks/generate-reports'
    | '/api/public/hooks/purge-retention'
    | '/api/public/hooks/scan-instagram'
    | '/api/public/hooks/scan-news'
    | '/api/public/evolution/webhook/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/adversaries'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/groups'
    | '/news'
    | '/onboarding'
    | '/people'
    | '/reports'
    | '/search'
    | '/settings'
    | '/sources'
    | '/territory'
    | '/alerts/$alertId'
    | '/reports/$reportId'
    | '/api/public/hooks/analyze-pending'
    | '/api/public/hooks/detect-alerts'
    | '/api/public/hooks/generate-reports'
    | '/api/public/hooks/purge-retention'
    | '/api/public/hooks/scan-instagram'
    | '/api/public/hooks/scan-news'
    | '/api/public/evolution/webhook/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/adversaries'
    | '/_authenticated/alerts'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/groups'
    | '/_authenticated/news'
    | '/_authenticated/onboarding'
    | '/_authenticated/people'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/sources'
    | '/_authenticated/territory'
    | '/_authenticated/alerts/$alertId'
    | '/_authenticated/reports/$reportId'
    | '/api/public/hooks/analyze-pending'
    | '/api/public/hooks/detect-alerts'
    | '/api/public/hooks/generate-reports'
    | '/api/public/hooks/purge-retention'
    | '/api/public/hooks/scan-instagram'
    | '/api/public/hooks/scan-news'
    | '/api/public/evolution/webhook/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAnalyzePendingRoute: typeof ApiPublicHooksAnalyzePendingRoute
  ApiPublicHooksDetectAlertsRoute: typeof ApiPublicHooksDetectAlertsRoute
  ApiPublicHooksGenerateReportsRoute: typeof ApiPublicHooksGenerateReportsRoute
  ApiPublicHooksPurgeRetentionRoute: typeof ApiPublicHooksPurgeRetentionRoute
  ApiPublicHooksScanInstagramRoute: typeof ApiPublicHooksScanInstagramRoute
  ApiPublicHooksScanNewsRoute: typeof ApiPublicHooksScanNewsRoute
  ApiPublicEvolutionWebhookTokenRoute: typeof ApiPublicEvolutionWebhookTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/territory': {
      id: '/_authenticated/territory'
      path: '/territory'
      fullPath: '/territory'
      preLoaderRoute: typeof AuthenticatedTerritoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adversaries': {
      id: '/_authenticated/adversaries'
      path: '/adversaries'
      fullPath: '/adversaries'
      preLoaderRoute: typeof AuthenticatedAdversariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/alerts/$alertId': {
      id: '/_authenticated/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AuthenticatedAlertsAlertIdRouteImport
      parentRoute: typeof AuthenticatedAlertsRoute
    }
    '/api/public/hooks/scan-news': {
      id: '/api/public/hooks/scan-news'
      path: '/api/public/hooks/scan-news'
      fullPath: '/api/public/hooks/scan-news'
      preLoaderRoute: typeof ApiPublicHooksScanNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-instagram': {
      id: '/api/public/hooks/scan-instagram'
      path: '/api/public/hooks/scan-instagram'
      fullPath: '/api/public/hooks/scan-instagram'
      preLoaderRoute: typeof ApiPublicHooksScanInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-retention': {
      id: '/api/public/hooks/purge-retention'
      path: '/api/public/hooks/purge-retention'
      fullPath: '/api/public/hooks/purge-retention'
      preLoaderRoute: typeof ApiPublicHooksPurgeRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-reports': {
      id: '/api/public/hooks/generate-reports'
      path: '/api/public/hooks/generate-reports'
      fullPath: '/api/public/hooks/generate-reports'
      preLoaderRoute: typeof ApiPublicHooksGenerateReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/detect-alerts': {
      id: '/api/public/hooks/detect-alerts'
      path: '/api/public/hooks/detect-alerts'
      fullPath: '/api/public/hooks/detect-alerts'
      preLoaderRoute: typeof ApiPublicHooksDetectAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/analyze-pending': {
      id: '/api/public/hooks/analyze-pending'
      path: '/api/public/hooks/analyze-pending'
      fullPath: '/api/public/hooks/analyze-pending'
      preLoaderRoute: typeof ApiPublicHooksAnalyzePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/webhook/$token': {
      id: '/api/public/evolution/webhook/$token'
      path: '/api/public/evolution/webhook/$token'
      fullPath: '/api/public/evolution/webhook/$token'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAlertsRouteChildren {
  AuthenticatedAlertsAlertIdRoute: typeof AuthenticatedAlertsAlertIdRoute
}

const AuthenticatedAlertsRouteChildren: AuthenticatedAlertsRouteChildren = {
  AuthenticatedAlertsAlertIdRoute: AuthenticatedAlertsAlertIdRoute,
}

const AuthenticatedAlertsRouteWithChildren =
  AuthenticatedAlertsRoute._addFileChildren(AuthenticatedAlertsRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdversariesRoute: typeof AuthenticatedAdversariesRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRouteWithChildren
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedTerritoryRoute: typeof AuthenticatedTerritoryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdversariesRoute: AuthenticatedAdversariesRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRouteWithChildren,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedTerritoryRoute: AuthenticatedTerritoryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAnalyzePendingRoute: ApiPublicHooksAnalyzePendingRoute,
  ApiPublicHooksDetectAlertsRoute: ApiPublicHooksDetectAlertsRoute,
  ApiPublicHooksGenerateReportsRoute: ApiPublicHooksGenerateReportsRoute,
  ApiPublicHooksPurgeRetentionRoute: ApiPublicHooksPurgeRetentionRoute,
  ApiPublicHooksScanInstagramRoute: ApiPublicHooksScanInstagramRoute,
  ApiPublicHooksScanNewsRoute: ApiPublicHooksScanNewsRoute,
  ApiPublicEvolutionWebhookTokenRoute: ApiPublicEvolutionWebhookTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
