/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SairRouteImport } from './routes/sair'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EleicaoRouteImport } from './routes/eleicao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteRouteImport } from './routes/site/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteIndexRouteImport } from './routes/site/index'
import { Route as SiteTermosRouteImport } from './routes/site/termos'
import { Route as SitePrivacidadeRouteImport } from './routes/site/privacidade'
import { Route as SiteLgpdRouteImport } from './routes/site/lgpd'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AppTerritorioRouteImport } from './routes/_app/territorio'
import { Route as AppSinaisRouteImport } from './routes/_app/sinais'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppRedeRouteImport } from './routes/_app/rede'
import { Route as AppPainelRouteImport } from './routes/_app/painel'
import { Route as AppCamaraRouteImport } from './routes/_app/camara'
import { Route as AppAlertasRouteImport } from './routes/_app/alertas'
import { Route as AppAjustesRouteRouteImport } from './routes/_app/ajustes/route'
import { Route as AppRelatoriosIndexRouteImport } from './routes/_app/relatorios.index'
import { Route as AppCamaraIndexRouteImport } from './routes/_app/camara.index'
import { Route as AppAlertasIndexRouteImport } from './routes/_app/alertas.index'
import { Route as AppAjustesIndexRouteImport } from './routes/_app/ajustes/index'
import { Route as AppRelatoriosReportIdRouteImport } from './routes/_app/relatorios.$reportId'
import { Route as AppCamaraVereadorIdRouteImport } from './routes/_app/camara.$vereadorId'
import { Route as AppAlertasAlertIdRouteImport } from './routes/_app/alertas.$alertId'
import { Route as AppAjustesWhatsappRouteImport } from './routes/_app/ajustes/whatsapp'
import { Route as AppAjustesOrganizacoesRouteImport } from './routes/_app/ajustes/organizacoes'
import { Route as AppAjustesNotificacoesRouteImport } from './routes/_app/ajustes/notificacoes'
import { Route as AppAjustesFontesRouteImport } from './routes/_app/ajustes/fontes'
import { Route as AppAjustesEquipeRouteImport } from './routes/_app/ajustes/equipe'
import { Route as AppAjustesEleitosRouteImport } from './routes/_app/ajustes/eleitos'
import { Route as AppAjustesAuditoriaRouteImport } from './routes/_app/ajustes/auditoria'
import { Route as ApiPublicHooksScanNewsRouteImport } from './routes/api/public/hooks/scan-news'
import { Route as ApiPublicHooksScanInstagramRouteImport } from './routes/api/public/hooks/scan-instagram'
import { Route as ApiPublicHooksPurgeRetentionRouteImport } from './routes/api/public/hooks/purge-retention'
import { Route as ApiPublicHooksGenerateReportsRouteImport } from './routes/api/public/hooks/generate-reports'
import { Route as ApiPublicHooksDetectAlertsRouteImport } from './routes/api/public/hooks/detect-alerts'
import { Route as ApiPublicHooksBackfillWhatsappRouteImport } from './routes/api/public/hooks/backfill-whatsapp'
import { Route as ApiPublicHooksAnalyzePendingRouteImport } from './routes/api/public/hooks/analyze-pending'
import { Route as ApiPublicEvolutionWebhookTokenRouteImport } from './routes/api/public/evolution.webhook.$token'

const SairRoute = SairRouteImport.update({
  id: '/sair',
  path: '/sair',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EleicaoRoute = EleicaoRouteImport.update({
  id: '/eleicao',
  path: '/eleicao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteTermosRoute = SiteTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePrivacidadeRoute = SitePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteLgpdRoute = SiteLgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => SiteRouteRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTerritorioRoute = AppTerritorioRouteImport.update({
  id: '/territorio',
  path: '/territorio',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSinaisRoute = AppSinaisRouteImport.update({
  id: '/sinais',
  path: '/sinais',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRedeRoute = AppRedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCamaraRoute = AppCamaraRouteImport.update({
  id: '/camara',
  path: '/camara',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesRouteRoute = AppAjustesRouteRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelatoriosIndexRoute = AppRelatoriosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRelatoriosRoute,
} as any)
const AppCamaraIndexRoute = AppCamaraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCamaraRoute,
} as any)
const AppAlertasIndexRoute = AppAlertasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlertasRoute,
} as any)
const AppAjustesIndexRoute = AppAjustesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppRelatoriosReportIdRoute = AppRelatoriosReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppRelatoriosRoute,
} as any)
const AppCamaraVereadorIdRoute = AppCamaraVereadorIdRouteImport.update({
  id: '/$vereadorId',
  path: '/$vereadorId',
  getParentRoute: () => AppCamaraRoute,
} as any)
const AppAlertasAlertIdRoute = AppAlertasAlertIdRouteImport.update({
  id: '/$alertId',
  path: '/$alertId',
  getParentRoute: () => AppAlertasRoute,
} as any)
const AppAjustesWhatsappRoute = AppAjustesWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppAjustesOrganizacoesRoute = AppAjustesOrganizacoesRouteImport.update({
  id: '/organizacoes',
  path: '/organizacoes',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppAjustesNotificacoesRoute = AppAjustesNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppAjustesFontesRoute = AppAjustesFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppAjustesEquipeRoute = AppAjustesEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppAjustesEleitosRoute = AppAjustesEleitosRouteImport.update({
  id: '/eleitos',
  path: '/eleitos',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const AppAjustesAuditoriaRoute = AppAjustesAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppAjustesRouteRoute,
} as any)
const ApiPublicHooksScanNewsRoute = ApiPublicHooksScanNewsRouteImport.update({
  id: '/api/public/hooks/scan-news',
  path: '/api/public/hooks/scan-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanInstagramRoute =
  ApiPublicHooksScanInstagramRouteImport.update({
    id: '/api/public/hooks/scan-instagram',
    path: '/api/public/hooks/scan-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPurgeRetentionRoute =
  ApiPublicHooksPurgeRetentionRouteImport.update({
    id: '/api/public/hooks/purge-retention',
    path: '/api/public/hooks/purge-retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateReportsRoute =
  ApiPublicHooksGenerateReportsRouteImport.update({
    id: '/api/public/hooks/generate-reports',
    path: '/api/public/hooks/generate-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDetectAlertsRoute =
  ApiPublicHooksDetectAlertsRouteImport.update({
    id: '/api/public/hooks/detect-alerts',
    path: '/api/public/hooks/detect-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillWhatsappRoute =
  ApiPublicHooksBackfillWhatsappRouteImport.update({
    id: '/api/public/hooks/backfill-whatsapp',
    path: '/api/public/hooks/backfill-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAnalyzePendingRoute =
  ApiPublicHooksAnalyzePendingRouteImport.update({
    id: '/api/public/hooks/analyze-pending',
    path: '/api/public/hooks/analyze-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionWebhookTokenRoute =
  ApiPublicEvolutionWebhookTokenRouteImport.update({
    id: '/api/public/evolution/webhook/$token',
    path: '/api/public/evolution/webhook/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/site': typeof SiteRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/eleicao': typeof EleicaoRoute
  '/entrar': typeof EntrarRoute
  '/sair': typeof SairRoute
  '/ajustes': typeof AppAjustesRouteRouteWithChildren
  '/alertas': typeof AppAlertasRouteWithChildren
  '/camara': typeof AppCamaraRouteWithChildren
  '/painel': typeof AppPainelRoute
  '/rede': typeof AppRedeRoute
  '/relatorios': typeof AppRelatoriosRouteWithChildren
  '/sinais': typeof AppSinaisRoute
  '/territorio': typeof AppTerritorioRoute
  '/r/$token': typeof RTokenRoute
  '/site/lgpd': typeof SiteLgpdRoute
  '/site/privacidade': typeof SitePrivacidadeRoute
  '/site/termos': typeof SiteTermosRoute
  '/site/': typeof SiteIndexRoute
  '/ajustes/auditoria': typeof AppAjustesAuditoriaRoute
  '/ajustes/eleitos': typeof AppAjustesEleitosRoute
  '/ajustes/equipe': typeof AppAjustesEquipeRoute
  '/ajustes/fontes': typeof AppAjustesFontesRoute
  '/ajustes/notificacoes': typeof AppAjustesNotificacoesRoute
  '/ajustes/organizacoes': typeof AppAjustesOrganizacoesRoute
  '/ajustes/whatsapp': typeof AppAjustesWhatsappRoute
  '/alertas/$alertId': typeof AppAlertasAlertIdRoute
  '/camara/$vereadorId': typeof AppCamaraVereadorIdRoute
  '/relatorios/$reportId': typeof AppRelatoriosReportIdRoute
  '/ajustes/': typeof AppAjustesIndexRoute
  '/alertas/': typeof AppAlertasIndexRoute
  '/camara/': typeof AppCamaraIndexRoute
  '/relatorios/': typeof AppRelatoriosIndexRoute
  '/api/public/hooks/analyze-pending': typeof ApiPublicHooksAnalyzePendingRoute
  '/api/public/hooks/backfill-whatsapp': typeof ApiPublicHooksBackfillWhatsappRoute
  '/api/public/hooks/detect-alerts': typeof ApiPublicHooksDetectAlertsRoute
  '/api/public/hooks/generate-reports': typeof ApiPublicHooksGenerateReportsRoute
  '/api/public/hooks/purge-retention': typeof ApiPublicHooksPurgeRetentionRoute
  '/api/public/hooks/scan-instagram': typeof ApiPublicHooksScanInstagramRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/evolution/webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eleicao': typeof EleicaoRoute
  '/entrar': typeof EntrarRoute
  '/sair': typeof SairRoute
  '/painel': typeof AppPainelRoute
  '/rede': typeof AppRedeRoute
  '/sinais': typeof AppSinaisRoute
  '/territorio': typeof AppTerritorioRoute
  '/r/$token': typeof RTokenRoute
  '/site/lgpd': typeof SiteLgpdRoute
  '/site/privacidade': typeof SitePrivacidadeRoute
  '/site/termos': typeof SiteTermosRoute
  '/site': typeof SiteIndexRoute
  '/ajustes/auditoria': typeof AppAjustesAuditoriaRoute
  '/ajustes/eleitos': typeof AppAjustesEleitosRoute
  '/ajustes/equipe': typeof AppAjustesEquipeRoute
  '/ajustes/fontes': typeof AppAjustesFontesRoute
  '/ajustes/notificacoes': typeof AppAjustesNotificacoesRoute
  '/ajustes/organizacoes': typeof AppAjustesOrganizacoesRoute
  '/ajustes/whatsapp': typeof AppAjustesWhatsappRoute
  '/alertas/$alertId': typeof AppAlertasAlertIdRoute
  '/camara/$vereadorId': typeof AppCamaraVereadorIdRoute
  '/relatorios/$reportId': typeof AppRelatoriosReportIdRoute
  '/ajustes': typeof AppAjustesIndexRoute
  '/alertas': typeof AppAlertasIndexRoute
  '/camara': typeof AppCamaraIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/api/public/hooks/analyze-pending': typeof ApiPublicHooksAnalyzePendingRoute
  '/api/public/hooks/backfill-whatsapp': typeof ApiPublicHooksBackfillWhatsappRoute
  '/api/public/hooks/detect-alerts': typeof ApiPublicHooksDetectAlertsRoute
  '/api/public/hooks/generate-reports': typeof ApiPublicHooksGenerateReportsRoute
  '/api/public/hooks/purge-retention': typeof ApiPublicHooksPurgeRetentionRoute
  '/api/public/hooks/scan-instagram': typeof ApiPublicHooksScanInstagramRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/evolution/webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/site': typeof SiteRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/eleicao': typeof EleicaoRoute
  '/entrar': typeof EntrarRoute
  '/sair': typeof SairRoute
  '/_app/ajustes': typeof AppAjustesRouteRouteWithChildren
  '/_app/alertas': typeof AppAlertasRouteWithChildren
  '/_app/camara': typeof AppCamaraRouteWithChildren
  '/_app/painel': typeof AppPainelRoute
  '/_app/rede': typeof AppRedeRoute
  '/_app/relatorios': typeof AppRelatoriosRouteWithChildren
  '/_app/sinais': typeof AppSinaisRoute
  '/_app/territorio': typeof AppTerritorioRoute
  '/r/$token': typeof RTokenRoute
  '/site/lgpd': typeof SiteLgpdRoute
  '/site/privacidade': typeof SitePrivacidadeRoute
  '/site/termos': typeof SiteTermosRoute
  '/site/': typeof SiteIndexRoute
  '/_app/ajustes/auditoria': typeof AppAjustesAuditoriaRoute
  '/_app/ajustes/eleitos': typeof AppAjustesEleitosRoute
  '/_app/ajustes/equipe': typeof AppAjustesEquipeRoute
  '/_app/ajustes/fontes': typeof AppAjustesFontesRoute
  '/_app/ajustes/notificacoes': typeof AppAjustesNotificacoesRoute
  '/_app/ajustes/organizacoes': typeof AppAjustesOrganizacoesRoute
  '/_app/ajustes/whatsapp': typeof AppAjustesWhatsappRoute
  '/_app/alertas/$alertId': typeof AppAlertasAlertIdRoute
  '/_app/camara/$vereadorId': typeof AppCamaraVereadorIdRoute
  '/_app/relatorios/$reportId': typeof AppRelatoriosReportIdRoute
  '/_app/ajustes/': typeof AppAjustesIndexRoute
  '/_app/alertas/': typeof AppAlertasIndexRoute
  '/_app/camara/': typeof AppCamaraIndexRoute
  '/_app/relatorios/': typeof AppRelatoriosIndexRoute
  '/api/public/hooks/analyze-pending': typeof ApiPublicHooksAnalyzePendingRoute
  '/api/public/hooks/backfill-whatsapp': typeof ApiPublicHooksBackfillWhatsappRoute
  '/api/public/hooks/detect-alerts': typeof ApiPublicHooksDetectAlertsRoute
  '/api/public/hooks/generate-reports': typeof ApiPublicHooksGenerateReportsRoute
  '/api/public/hooks/purge-retention': typeof ApiPublicHooksPurgeRetentionRoute
  '/api/public/hooks/scan-instagram': typeof ApiPublicHooksScanInstagramRoute
  '/api/public/hooks/scan-news': typeof ApiPublicHooksScanNewsRoute
  '/api/public/evolution/webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/site'
    | '/admin'
    | '/eleicao'
    | '/entrar'
    | '/sair'
    | '/ajustes'
    | '/alertas'
    | '/camara'
    | '/painel'
    | '/rede'
    | '/relatorios'
    | '/sinais'
    | '/territorio'
    | '/r/$token'
    | '/site/lgpd'
    | '/site/privacidade'
    | '/site/termos'
    | '/site/'
    | '/ajustes/auditoria'
    | '/ajustes/eleitos'
    | '/ajustes/equipe'
    | '/ajustes/fontes'
    | '/ajustes/notificacoes'
    | '/ajustes/organizacoes'
    | '/ajustes/whatsapp'
    | '/alertas/$alertId'
    | '/camara/$vereadorId'
    | '/relatorios/$reportId'
    | '/ajustes/'
    | '/alertas/'
    | '/camara/'
    | '/relatorios/'
    | '/api/public/hooks/analyze-pending'
    | '/api/public/hooks/backfill-whatsapp'
    | '/api/public/hooks/detect-alerts'
    | '/api/public/hooks/generate-reports'
    | '/api/public/hooks/purge-retention'
    | '/api/public/hooks/scan-instagram'
    | '/api/public/hooks/scan-news'
    | '/api/public/evolution/webhook/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/eleicao'
    | '/entrar'
    | '/sair'
    | '/painel'
    | '/rede'
    | '/sinais'
    | '/territorio'
    | '/r/$token'
    | '/site/lgpd'
    | '/site/privacidade'
    | '/site/termos'
    | '/site'
    | '/ajustes/auditoria'
    | '/ajustes/eleitos'
    | '/ajustes/equipe'
    | '/ajustes/fontes'
    | '/ajustes/notificacoes'
    | '/ajustes/organizacoes'
    | '/ajustes/whatsapp'
    | '/alertas/$alertId'
    | '/camara/$vereadorId'
    | '/relatorios/$reportId'
    | '/ajustes'
    | '/alertas'
    | '/camara'
    | '/relatorios'
    | '/api/public/hooks/analyze-pending'
    | '/api/public/hooks/backfill-whatsapp'
    | '/api/public/hooks/detect-alerts'
    | '/api/public/hooks/generate-reports'
    | '/api/public/hooks/purge-retention'
    | '/api/public/hooks/scan-instagram'
    | '/api/public/hooks/scan-news'
    | '/api/public/evolution/webhook/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/site'
    | '/admin'
    | '/eleicao'
    | '/entrar'
    | '/sair'
    | '/_app/ajustes'
    | '/_app/alertas'
    | '/_app/camara'
    | '/_app/painel'
    | '/_app/rede'
    | '/_app/relatorios'
    | '/_app/sinais'
    | '/_app/territorio'
    | '/r/$token'
    | '/site/lgpd'
    | '/site/privacidade'
    | '/site/termos'
    | '/site/'
    | '/_app/ajustes/auditoria'
    | '/_app/ajustes/eleitos'
    | '/_app/ajustes/equipe'
    | '/_app/ajustes/fontes'
    | '/_app/ajustes/notificacoes'
    | '/_app/ajustes/organizacoes'
    | '/_app/ajustes/whatsapp'
    | '/_app/alertas/$alertId'
    | '/_app/camara/$vereadorId'
    | '/_app/relatorios/$reportId'
    | '/_app/ajustes/'
    | '/_app/alertas/'
    | '/_app/camara/'
    | '/_app/relatorios/'
    | '/api/public/hooks/analyze-pending'
    | '/api/public/hooks/backfill-whatsapp'
    | '/api/public/hooks/detect-alerts'
    | '/api/public/hooks/generate-reports'
    | '/api/public/hooks/purge-retention'
    | '/api/public/hooks/scan-instagram'
    | '/api/public/hooks/scan-news'
    | '/api/public/evolution/webhook/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  EleicaoRoute: typeof EleicaoRoute
  EntrarRoute: typeof EntrarRoute
  SairRoute: typeof SairRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicHooksAnalyzePendingRoute: typeof ApiPublicHooksAnalyzePendingRoute
  ApiPublicHooksBackfillWhatsappRoute: typeof ApiPublicHooksBackfillWhatsappRoute
  ApiPublicHooksDetectAlertsRoute: typeof ApiPublicHooksDetectAlertsRoute
  ApiPublicHooksGenerateReportsRoute: typeof ApiPublicHooksGenerateReportsRoute
  ApiPublicHooksPurgeRetentionRoute: typeof ApiPublicHooksPurgeRetentionRoute
  ApiPublicHooksScanInstagramRoute: typeof ApiPublicHooksScanInstagramRoute
  ApiPublicHooksScanNewsRoute: typeof ApiPublicHooksScanNewsRoute
  ApiPublicEvolutionWebhookTokenRoute: typeof ApiPublicEvolutionWebhookTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sair': {
      id: '/sair'
      path: '/sair'
      fullPath: '/sair'
      preLoaderRoute: typeof SairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleicao': {
      id: '/eleicao'
      path: '/eleicao'
      fullPath: '/eleicao'
      preLoaderRoute: typeof EleicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/site/termos': {
      id: '/site/termos'
      path: '/termos'
      fullPath: '/site/termos'
      preLoaderRoute: typeof SiteTermosRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/site/privacidade': {
      id: '/site/privacidade'
      path: '/privacidade'
      fullPath: '/site/privacidade'
      preLoaderRoute: typeof SitePrivacidadeRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/site/lgpd': {
      id: '/site/lgpd'
      path: '/lgpd'
      fullPath: '/site/lgpd'
      preLoaderRoute: typeof SiteLgpdRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/territorio': {
      id: '/_app/territorio'
      path: '/territorio'
      fullPath: '/territorio'
      preLoaderRoute: typeof AppTerritorioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sinais': {
      id: '/_app/sinais'
      path: '/sinais'
      fullPath: '/sinais'
      preLoaderRoute: typeof AppSinaisRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rede': {
      id: '/_app/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof AppRedeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/camara': {
      id: '/_app/camara'
      path: '/camara'
      fullPath: '/camara'
      preLoaderRoute: typeof AppCamaraRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/relatorios/': {
      id: '/_app/relatorios/'
      path: '/'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AppRelatoriosIndexRouteImport
      parentRoute: typeof AppRelatoriosRoute
    }
    '/_app/camara/': {
      id: '/_app/camara/'
      path: '/'
      fullPath: '/camara/'
      preLoaderRoute: typeof AppCamaraIndexRouteImport
      parentRoute: typeof AppCamaraRoute
    }
    '/_app/alertas/': {
      id: '/_app/alertas/'
      path: '/'
      fullPath: '/alertas/'
      preLoaderRoute: typeof AppAlertasIndexRouteImport
      parentRoute: typeof AppAlertasRoute
    }
    '/_app/ajustes/': {
      id: '/_app/ajustes/'
      path: '/'
      fullPath: '/ajustes/'
      preLoaderRoute: typeof AppAjustesIndexRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/relatorios/$reportId': {
      id: '/_app/relatorios/$reportId'
      path: '/$reportId'
      fullPath: '/relatorios/$reportId'
      preLoaderRoute: typeof AppRelatoriosReportIdRouteImport
      parentRoute: typeof AppRelatoriosRoute
    }
    '/_app/camara/$vereadorId': {
      id: '/_app/camara/$vereadorId'
      path: '/$vereadorId'
      fullPath: '/camara/$vereadorId'
      preLoaderRoute: typeof AppCamaraVereadorIdRouteImport
      parentRoute: typeof AppCamaraRoute
    }
    '/_app/alertas/$alertId': {
      id: '/_app/alertas/$alertId'
      path: '/$alertId'
      fullPath: '/alertas/$alertId'
      preLoaderRoute: typeof AppAlertasAlertIdRouteImport
      parentRoute: typeof AppAlertasRoute
    }
    '/_app/ajustes/whatsapp': {
      id: '/_app/ajustes/whatsapp'
      path: '/whatsapp'
      fullPath: '/ajustes/whatsapp'
      preLoaderRoute: typeof AppAjustesWhatsappRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/ajustes/organizacoes': {
      id: '/_app/ajustes/organizacoes'
      path: '/organizacoes'
      fullPath: '/ajustes/organizacoes'
      preLoaderRoute: typeof AppAjustesOrganizacoesRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/ajustes/notificacoes': {
      id: '/_app/ajustes/notificacoes'
      path: '/notificacoes'
      fullPath: '/ajustes/notificacoes'
      preLoaderRoute: typeof AppAjustesNotificacoesRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/ajustes/fontes': {
      id: '/_app/ajustes/fontes'
      path: '/fontes'
      fullPath: '/ajustes/fontes'
      preLoaderRoute: typeof AppAjustesFontesRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/ajustes/equipe': {
      id: '/_app/ajustes/equipe'
      path: '/equipe'
      fullPath: '/ajustes/equipe'
      preLoaderRoute: typeof AppAjustesEquipeRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/ajustes/eleitos': {
      id: '/_app/ajustes/eleitos'
      path: '/eleitos'
      fullPath: '/ajustes/eleitos'
      preLoaderRoute: typeof AppAjustesEleitosRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/_app/ajustes/auditoria': {
      id: '/_app/ajustes/auditoria'
      path: '/auditoria'
      fullPath: '/ajustes/auditoria'
      preLoaderRoute: typeof AppAjustesAuditoriaRouteImport
      parentRoute: typeof AppAjustesRouteRoute
    }
    '/api/public/hooks/scan-news': {
      id: '/api/public/hooks/scan-news'
      path: '/api/public/hooks/scan-news'
      fullPath: '/api/public/hooks/scan-news'
      preLoaderRoute: typeof ApiPublicHooksScanNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-instagram': {
      id: '/api/public/hooks/scan-instagram'
      path: '/api/public/hooks/scan-instagram'
      fullPath: '/api/public/hooks/scan-instagram'
      preLoaderRoute: typeof ApiPublicHooksScanInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-retention': {
      id: '/api/public/hooks/purge-retention'
      path: '/api/public/hooks/purge-retention'
      fullPath: '/api/public/hooks/purge-retention'
      preLoaderRoute: typeof ApiPublicHooksPurgeRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-reports': {
      id: '/api/public/hooks/generate-reports'
      path: '/api/public/hooks/generate-reports'
      fullPath: '/api/public/hooks/generate-reports'
      preLoaderRoute: typeof ApiPublicHooksGenerateReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/detect-alerts': {
      id: '/api/public/hooks/detect-alerts'
      path: '/api/public/hooks/detect-alerts'
      fullPath: '/api/public/hooks/detect-alerts'
      preLoaderRoute: typeof ApiPublicHooksDetectAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-whatsapp': {
      id: '/api/public/hooks/backfill-whatsapp'
      path: '/api/public/hooks/backfill-whatsapp'
      fullPath: '/api/public/hooks/backfill-whatsapp'
      preLoaderRoute: typeof ApiPublicHooksBackfillWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/analyze-pending': {
      id: '/api/public/hooks/analyze-pending'
      path: '/api/public/hooks/analyze-pending'
      fullPath: '/api/public/hooks/analyze-pending'
      preLoaderRoute: typeof ApiPublicHooksAnalyzePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/webhook/$token': {
      id: '/api/public/evolution/webhook/$token'
      path: '/api/public/evolution/webhook/$token'
      fullPath: '/api/public/evolution/webhook/$token'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAjustesRouteRouteChildren {
  AppAjustesAuditoriaRoute: typeof AppAjustesAuditoriaRoute
  AppAjustesEleitosRoute: typeof AppAjustesEleitosRoute
  AppAjustesEquipeRoute: typeof AppAjustesEquipeRoute
  AppAjustesFontesRoute: typeof AppAjustesFontesRoute
  AppAjustesNotificacoesRoute: typeof AppAjustesNotificacoesRoute
  AppAjustesOrganizacoesRoute: typeof AppAjustesOrganizacoesRoute
  AppAjustesWhatsappRoute: typeof AppAjustesWhatsappRoute
  AppAjustesIndexRoute: typeof AppAjustesIndexRoute
}

const AppAjustesRouteRouteChildren: AppAjustesRouteRouteChildren = {
  AppAjustesAuditoriaRoute: AppAjustesAuditoriaRoute,
  AppAjustesEleitosRoute: AppAjustesEleitosRoute,
  AppAjustesEquipeRoute: AppAjustesEquipeRoute,
  AppAjustesFontesRoute: AppAjustesFontesRoute,
  AppAjustesNotificacoesRoute: AppAjustesNotificacoesRoute,
  AppAjustesOrganizacoesRoute: AppAjustesOrganizacoesRoute,
  AppAjustesWhatsappRoute: AppAjustesWhatsappRoute,
  AppAjustesIndexRoute: AppAjustesIndexRoute,
}

const AppAjustesRouteRouteWithChildren = AppAjustesRouteRoute._addFileChildren(
  AppAjustesRouteRouteChildren,
)

interface AppAlertasRouteChildren {
  AppAlertasAlertIdRoute: typeof AppAlertasAlertIdRoute
  AppAlertasIndexRoute: typeof AppAlertasIndexRoute
}

const AppAlertasRouteChildren: AppAlertasRouteChildren = {
  AppAlertasAlertIdRoute: AppAlertasAlertIdRoute,
  AppAlertasIndexRoute: AppAlertasIndexRoute,
}

const AppAlertasRouteWithChildren = AppAlertasRoute._addFileChildren(
  AppAlertasRouteChildren,
)

interface AppCamaraRouteChildren {
  AppCamaraVereadorIdRoute: typeof AppCamaraVereadorIdRoute
  AppCamaraIndexRoute: typeof AppCamaraIndexRoute
}

const AppCamaraRouteChildren: AppCamaraRouteChildren = {
  AppCamaraVereadorIdRoute: AppCamaraVereadorIdRoute,
  AppCamaraIndexRoute: AppCamaraIndexRoute,
}

const AppCamaraRouteWithChildren = AppCamaraRoute._addFileChildren(
  AppCamaraRouteChildren,
)

interface AppRelatoriosRouteChildren {
  AppRelatoriosReportIdRoute: typeof AppRelatoriosReportIdRoute
  AppRelatoriosIndexRoute: typeof AppRelatoriosIndexRoute
}

const AppRelatoriosRouteChildren: AppRelatoriosRouteChildren = {
  AppRelatoriosReportIdRoute: AppRelatoriosReportIdRoute,
  AppRelatoriosIndexRoute: AppRelatoriosIndexRoute,
}

const AppRelatoriosRouteWithChildren = AppRelatoriosRoute._addFileChildren(
  AppRelatoriosRouteChildren,
)

interface AppRouteRouteChildren {
  AppAjustesRouteRoute: typeof AppAjustesRouteRouteWithChildren
  AppAlertasRoute: typeof AppAlertasRouteWithChildren
  AppCamaraRoute: typeof AppCamaraRouteWithChildren
  AppPainelRoute: typeof AppPainelRoute
  AppRedeRoute: typeof AppRedeRoute
  AppRelatoriosRoute: typeof AppRelatoriosRouteWithChildren
  AppSinaisRoute: typeof AppSinaisRoute
  AppTerritorioRoute: typeof AppTerritorioRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAjustesRouteRoute: AppAjustesRouteRouteWithChildren,
  AppAlertasRoute: AppAlertasRouteWithChildren,
  AppCamaraRoute: AppCamaraRouteWithChildren,
  AppPainelRoute: AppPainelRoute,
  AppRedeRoute: AppRedeRoute,
  AppRelatoriosRoute: AppRelatoriosRouteWithChildren,
  AppSinaisRoute: AppSinaisRoute,
  AppTerritorioRoute: AppTerritorioRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SiteRouteRouteChildren {
  SiteLgpdRoute: typeof SiteLgpdRoute
  SitePrivacidadeRoute: typeof SitePrivacidadeRoute
  SiteTermosRoute: typeof SiteTermosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteLgpdRoute: SiteLgpdRoute,
  SitePrivacidadeRoute: SitePrivacidadeRoute,
  SiteTermosRoute: SiteTermosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  EleicaoRoute: EleicaoRoute,
  EntrarRoute: EntrarRoute,
  SairRoute: SairRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicHooksAnalyzePendingRoute: ApiPublicHooksAnalyzePendingRoute,
  ApiPublicHooksBackfillWhatsappRoute: ApiPublicHooksBackfillWhatsappRoute,
  ApiPublicHooksDetectAlertsRoute: ApiPublicHooksDetectAlertsRoute,
  ApiPublicHooksGenerateReportsRoute: ApiPublicHooksGenerateReportsRoute,
  ApiPublicHooksPurgeRetentionRoute: ApiPublicHooksPurgeRetentionRoute,
  ApiPublicHooksScanInstagramRoute: ApiPublicHooksScanInstagramRoute,
  ApiPublicHooksScanNewsRoute: ApiPublicHooksScanNewsRoute,
  ApiPublicEvolutionWebhookTokenRoute: ApiPublicEvolutionWebhookTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
